#!/bin/sh

DESC="MysqlMonk"
NAME=mysqlmonk
PIDFILE=/var/run/$NAME.pid
RUN_AS=root
COMMAND="/usr/bin/java -- -jar /usr/local/mysqlmonk/mysqlmonk.jar -c /usr/local/mysqlmonk/conf/monk.conf"

d_start() {
	/sbin/start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --chuid $RUN_AS --exec $COMMAND
}

d_stop() {
	/sbin/start-stop-daemon --stop --quiet --pidfile $PIDFILE
	if [ -e $PIDFILE ]
		then rm $PIDFILE
	fi
}

case $1 in
	start)
	echo -n "Starting $DESC: $NAME"
	d_start
	echo "."
	;;
	stop)
	echo -n "Stopping $DESC: $NAME"
	d_stop
	echo "."
	;;
	restart)
	echo -n "Restarting $DESC: $NAME"
	d_stop
	sleep 1
	d_start
	echo "."
	;;
	*)
	echo "usage: $NAME {start|stop|restart}"
	exit 1
	;;
esac

exit 0
